version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mr_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mr_network

  redis:
    image: redis:7.2-alpine
    container_name: mr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mr_network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mr_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/mr_communication?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key
      NODE_ENV: production
      WHATSAPP_ACCESS_TOKEN: qt3yb4Lgty5SjeJeflqEYvdWJy9id8IzpC3Ha4C1M5jtaBomySZFJ4aXQIRN4uN4
      WHATSAPP_PHONE_NUMBER_ID: 778806801982541
      WHATSAPP_VERIFY_TOKEN: token1234
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - mr_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mr_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - mr_network

volumes:
  mongodb_data:
  redis_data:

networks:
  mr_network:
    driver: bridge
